ADMassignment/Models/Produkt.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ADMassignment.Models
{
    public class Produkt
    {
        public int Id { get; set; }
        [StringLength(60, MinimumLength = 3), Required]
        public string Title { get; set; }

        [Display(Name = "Best Before Date"), DataType(DataType.Date)]
        public DateTime BestBeforeDate { get; set; }
        
        [Range(1, 100), DataType(DataType.Currency)]
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Price { get; set; }

        [RegularExpression(@"[A-Z]+[a-zA-Z""'\s-]*$"),StringLength(30)]
        [Required]
        public string Flavor { get; set; }

        [RegularExpression(@"[A-Z]+[a-zA-Z0-9""'\s-]*$"),StringLength(5)]
        [Required]
        public string Rating { get; set; }
    }
}

ADMassignment/Controllers/ProduktsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ADMassignment.Data;
using ADMassignment.Models;

namespace ADMassignment.Controllers
{
    public class ProduktsController : Controller
    {
        private readonly AdmProduktContext _context;

        public ProduktsController(AdmProduktContext context)
        {
            _context = context;
        }

        // GET: Produkts
        public async Task<IActionResult> Index(string produktFlavor, string searchString)
        {
            //Use LINQ to het list of flavors
            IQueryable<string> genreQuery = from m in _context.Produkt
                                            orderby m.Flavor
                                            select m.Flavor;

            var produkts = from m in _context.Produkt
                         select m;

            if (!string.IsNullOrEmpty(searchString))
            {
                produkts = produkts.Where(s => s.Title.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(produktFlavor))
            {
                produkts = produkts.Where(x => x.Flavor == produktFlavor);
            }

            var produktFlavorVM = new ProduktFlavorViewModel
            {
                Flavors = new SelectList(await genreQuery.Distinct().ToListAsync()),
                Produkts = await produkts.ToListAsync()
            };

            return View(produktFlavorVM);
        }

        // GET: Produkts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produkt = await _context.Produkt
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produkt == null)
            {
                return NotFound();
            }

            return View(produkt);
        }

        // GET: Produkts/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Produkts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,BestBeforeDate,Flavor,Price,Rating")] Produkt produkt)
        {
            if (ModelState.IsValid)
            {
                _context.Add(produkt);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(produkt);
        }

        // GET: Produkts/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produkt = await _context.Produkt.FindAsync(id);
            if (produkt == null)
            {
                return NotFound();
            }
            return View(produkt);
        }

        // POST: Produkts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,BestBeforeDate,Flavor,Price,Rating")] Produkt produkt)
        {
            if (id != produkt.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(produkt);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProduktExists(produkt.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(produkt);
        }

        // GET: Produkts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var produkt = await _context.Produkt
                .FirstOrDefaultAsync(m => m.Id == id);
            if (produkt == null)
            {
                return NotFound();
            }

            return View(produkt);
        }

        // POST: Produkts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var produkt = await _context.Produkt.FindAsync(id);
            _context.Produkt.Remove(produkt);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ProduktExists(int id)
        {
            return _context.Produkt.Any(e => e.Id == id);
        }
    }
}

ADMassignment/Views/Produkts/Create.cshtml
@model ADMassignment.Models.Produkt

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Produkt</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BestBeforeDate" class="control-label"></label>
                <input asp-for="BestBeforeDate" class="form-control" />
                <span asp-validation-for="BestBeforeDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Flavor" class="control-label"></label>
                <input asp-for="Flavor" class="form-control" />
                <span asp-validation-for="Flavor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ADMassignment/Views/Produkts/Delete.cshtml
@model ADMassignment.Models.Produkt

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Produkt</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.BestBeforeDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.BestBeforeDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Flavor)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Flavor)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ADMassignment/Views/Produkts/Details.cshtml
@model ADMassignment.Models.Produkt

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Produkt</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.BestBeforeDate)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.BestBeforeDate)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Flavor)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Flavor)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ADMassignment/Views/Produkts/Edit.cshtml
@model ADMassignment.Models.Produkt

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Produkt</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="BestBeforeDate" class="control-label"></label>
                <input asp-for="BestBeforeDate" class="form-control" />
                <span asp-validation-for="BestBeforeDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Flavor" class="control-label"></label>
                <input asp-for="Flavor" class="form-control" />
                <span asp-validation-for="Flavor" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ADMassignment/Views/Produkts/Index.cshtml
@model ADMassignment.Models.ProduktFlavorViewModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Produkts" asp-action="Index" method="get">
    <p>
        <select asp-for="ProduktFlavor" asp-items="Model.Flavors">
            <option value="">All</option>
        </select>

        Title: <input type="text" name="SearchString">
        <input type="submit" value="Filter" />
    </p>
</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Produkts[0].Title)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Produkts[0].BestBeforeDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Produkts[0].Flavor)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Produkts[0].Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Produkts[0].Rating)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Produkts) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Title)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BestBeforeDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Flavor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Rating)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>